### ISSUE TITLE
In type: ";" Matrix, using type ##G

### ISSUE THREAD

**Issue by jrgonzalezrios** [TechoGT/survey-mobile-app#15]
If two type: Gender is present in matrix of text, you cant not select the same answer in two questions, it makes it exclusive

**Comment by humbertn** [comment]
I just found the error, and it's not the type G, its on a type Yes/No, it makes it exclusive.

**Comment by humbertn** [comment]
Resolved #15 in commit 84bd938946a4246a76ea4f7a5cc7fddf3ca175dc
