### ISSUE TITLE
Bower dependecies in codebase

### ISSUE THREAD

**Issue by jossemarGT** [TechoGT/survey-mobile-app#3]
Hello!

I was looking at your source code but I found that you have ngCordova as part of your codebase, I think that isn't a good idea to have a dependency as part of your code, also is even more tempting to even modify that dependency, tightly coupling it to our solution.

Regards :octocat:

**Comment by humbertn** [comment]
Thanks for your pull request, it was accepted, and the fixes that you recommended were applied.
