### ISSUE TITLE
Backendless development

### ISSUE THREAD

**Issue by jossemarGT** [TechoGT/survey-mobile-app#4]
Hello!

I was trying to play with your app (as developer), but, it looks like that I can't implement a new feature if it isn't published in your public API, have you thought to code an API mock in the application to test locally new features ?

Regards :octocat:

**Comment by humbertn** [comment]
Hello @jossemarGT,

Thanks for the interest on survey-mobile-app, I just added a API response example for backendless testing, you can find it on: _API-response-exaple/survey_949485.json_, you just have add this Json on _$localStorage_ and name it 'surveys'. 

If this works for you, please close this issue. :bowtie:
